apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tyyj8tejv-go 
  janus-idp.io/tekton: tyyj8tejv-go
  backstage.io/kubernetes-id: tyyj8tejv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tyyj8tejv-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  