apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tyyj8tejv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tyyj8tejv-go 
  name: tyyj8tejv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tyyj8tejv-go 
